services:
  db:
    image: postgres:18-alpine
    container_name: nuzlucke-db
    env_file: .env
    ports:
      - "5432:5432"
    profiles: ["ui","init", "backend", "db"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - nuzlucke-data:/var/lib/postgresql/data
      - ./database/queries/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./database/queries:/schema_files:ro #marked as readonly so they can't be tampered with
  loader:
    build:
      context: ./pokemon_data_loader
      dockerfile: Dockerfile
    container_name: nuzlucke-loader
    env_file: .env
    profiles: ["init"]
    environment:
      - DOCKER_CONTAINER=true
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  backend:
    container_name: nuzlucke-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    profiles: ["ui","init"] 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      loader:
        condition: service_completed_successfully
  frontend:
    container_name: nuzlucke-frontend
    profiles: ["backend","init"] 
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL} 
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  nuzlucke-data: