services:
  db:
    build: .
    container_name: nuzlucke
    restart: always
    env_file:
      - ../pokemon_data_loader/.env
    volumes:
      - nuzlucke:/var/lib/postgresql
      - ./queries:/docker-entrypoint-initdb.d
      - ../pokemon_data_loader:/app/src
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  nuzlucke: