name: Check Dependencies with Renovate

on:
  # Run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v44.2.6
        with:
          configurationFile: renovate.json
          token: '${{ secrets.RENOVATE_TOKEN }}'
